import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'earlzero' at '20.08.15 0:48' with Gradle 2.2.1
 *
 * @author earlzero, @date 20.08.15 0:48
 */
public class Library {
	public static void main(String... args) {
		Client client = ClientBuilder.newClient();
		WebTarget target = client.target("http://localhost:8080/").path("hello").path("test");
		Invocation.Builder invocationBuilder = target.request(MediaType.TEXT_PLAIN_TYPE);
		invocationBuilder.header("some-header", "true");
		Response response = invocationBuilder.get();
		System.out.println(response.readEntity(String.class));
	}
}
